### ISSUE TITLE
Clashing name with existing project

### ISSUE THREAD

**Issue by ademariag** [ermontgo/kapitan#1]
Hey, cool project! 

We have a very similar project also called Kapitan (https://github.com/deepmind/kapitan/), with very similar approach (probably driven by the same frustrations!)

Given that we operate in the same Kubernetes space, do you think it would be possible to rename your project to avoid confusing our and you users?

Do come visit on the kubernetes slack #kapitan channel if you want to learn how we are tackling the same issues.

**Comment by uberspot** [comment]
+1

**Comment by ermontgo** [comment]
Hey, thanks for reaching out. I don't know how I missed you guys as I was checking the name out!

I totally agree we want to avoid confusing everyone. I will start the process of renaming.

Thanks!
